server:
  port: 1001

management:
  endpoints:
    web:
      exposure:
        include: "*"

  tracing:
    sampling:
      probability: 1.0

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

####################
# circuit breaker
####################

resilience4j:
  circuitbreaker:
    instances:
      ecommBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED